# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/anderson/vivado/project/Activation_accelerator/Activation_accelerator.srcs/sources_1/bd/design_1/ip/design_1_accumulator_0_0/design_1_accumulator_0_0.xci
# IP: The module: 'design_1_accumulator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/anderson/vivado/project/Activation_accelerator/Activation_accelerator.srcs/sources_1/ip/c_shift_ram_2/c_shift_ram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_shift_ram_2 || ORIG_REF_NAME==c_shift_ram_2} -quiet] -quiet

# IP: /home/anderson/vivado/project/Activation_accelerator/Activation_accelerator.srcs/sources_1/ip/floating_point_1/floating_point_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_1 || ORIG_REF_NAME==floating_point_1} -quiet] -quiet

# IP: /home/anderson/vivado/project/Activation_accelerator/Activation_accelerator.srcs/sources_1/ip/floating_point_2/floating_point_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_2 || ORIG_REF_NAME==floating_point_2} -quiet] -quiet

# IP: /home/anderson/vivado/project/Activation_accelerator/Activation_accelerator.srcs/sources_1/ip/c_shift_ram_1/c_shift_ram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_shift_ram_1 || ORIG_REF_NAME==c_shift_ram_1} -quiet] -quiet

# XDC: /home/anderson/vivado/project/Activation_accelerator/Activation_accelerator.gen/sources_1/bd/design_1/ip/design_1_accumulator_0_0/design_1_accumulator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_accumulator_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/anderson/vivado/project/Activation_accelerator/Activation_accelerator.srcs/sources_1/bd/design_1/ip/design_1_accumulator_0_0/design_1_accumulator_0_0.xci
# IP: The module: 'design_1_accumulator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/anderson/vivado/project/Activation_accelerator/Activation_accelerator.srcs/sources_1/ip/c_shift_ram_2/c_shift_ram_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_shift_ram_2 || ORIG_REF_NAME==c_shift_ram_2} -quiet] -quiet

# IP: /home/anderson/vivado/project/Activation_accelerator/Activation_accelerator.srcs/sources_1/ip/floating_point_1/floating_point_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_1 || ORIG_REF_NAME==floating_point_1} -quiet] -quiet

# IP: /home/anderson/vivado/project/Activation_accelerator/Activation_accelerator.srcs/sources_1/ip/floating_point_2/floating_point_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_2 || ORIG_REF_NAME==floating_point_2} -quiet] -quiet

# IP: /home/anderson/vivado/project/Activation_accelerator/Activation_accelerator.srcs/sources_1/ip/c_shift_ram_1/c_shift_ram_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_shift_ram_1 || ORIG_REF_NAME==c_shift_ram_1} -quiet] -quiet

# XDC: /home/anderson/vivado/project/Activation_accelerator/Activation_accelerator.gen/sources_1/bd/design_1/ip/design_1_accumulator_0_0/design_1_accumulator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_accumulator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
