# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/anderson/vivado/project/Activation_accelerator/Activation_accelerator.srcs/sources_1/ip/floating_point_fixed/floating_point_fixed.xci
# IP: The module: 'floating_point_fixed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anderson/vivado/project/Activation_accelerator/Activation_accelerator.gen/sources_1/ip/floating_point_fixed/floating_point_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_fixed'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/anderson/vivado/project/Activation_accelerator/Activation_accelerator.srcs/sources_1/ip/floating_point_fixed/floating_point_fixed.xci
# IP: The module: 'floating_point_fixed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anderson/vivado/project/Activation_accelerator/Activation_accelerator.gen/sources_1/ip/floating_point_fixed/floating_point_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_fixed'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
