######################################################################
#
# File name : block_tb_simulate.do
# Created on: Thu Oct 09 20:48:48 CST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.block_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {block_tb_wave.do}

view wave
view structure
view signals

do {block_tb.udo}

run 1000ns
