######################################################################
#
# File name : block_tb_compile.do
# Created on: Thu Oct 09 20:48:48 CST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/work
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/msim

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/msim/xil_defaultlib

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlog -64 -incr -mfcu -work xil_defaultlib  \
"../../../../Activation_accelerator.srcs/sources_1/new/exp.v" \
"../../../../Activation_accelerator.srcs/sources_1/new/exp_from_uv.v" \
"../../../../Activation_accelerator.srcs/sources_1/new/get_u_v.v" \
"../../../../Activation_accelerator.srcs/sources_1/new/multiple_log2e.v" \
"../../../../Activation_accelerator.srcs/sim_1/new/block_tb.v" \


# compile glbl module
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlog -work xil_defaultlib "glbl.v"

