######################################################################
#
# File name : block_tb_compile.do
# Created on: Wed Oct 08 16:59:18 CST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/work
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/msim

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/msim/xil_defaultlib

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlog -64 -incr -mfcu -work xil_defaultlib  \
"../../../../Activation_accelerator.srcs/sources_1/new/multiple_log2e.v" \
"../../../../Activation_accelerator.srcs/sources_1/new/get_u_v.v" \
"../../../../Activation_accelerator.srcs/sources_1/new/exp_from_uv.v" \
"../../../../Activation_accelerator.ip_user_files/bd/design_1/ip/design_1_multiple_log2e_0_0/sim/design_1_multiple_log2e_0_0.v" \
"../../../../Activation_accelerator.ip_user_files/bd/design_1/ip/design_1_get_u_v_0_0/sim/design_1_get_u_v_0_0.v" \
"../../../../Activation_accelerator.ip_user_files/bd/design_1/ip/design_1_exp_from_uv_0_0/sim/design_1_exp_from_uv_0_0.v" \
"../../../../Activation_accelerator.ip_user_files/bd/design_1/sim/design_1.v" \
"../../../../Activation_accelerator.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v" \
"../../../../Activation_accelerator.srcs/sim_1/new/block_tb.v" \


# compile glbl module
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlog -work xil_defaultlib "glbl.v"

