######################################################################
#
# File name : block_tb_wave.do
# Created on: Thu Oct 16 10:14:58 CST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
