######################################################################
#
# File name : block_tb_wave.do
# Created on: Sat Oct 18 12:00:45 CST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
