######################################################################
#
# File name : block_tb_wave.do
# Created on: Tue Oct 21 16:54:58 CST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
