#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Siemens ModelSim Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Mon Sep 29 17:22:55 CST 2025
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
bin_path="/home/anderson/intelFPGA/20.1/modelsim_ase/bin"
set -Eeuo pipefail
source block_tb_compile.do 2>&1 | tee compile.log

